'use strict';
const E=window.DemoEngine,$=s=>document.querySelector(s),workspace=$('#workspace');
let requests=[],current='finance';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=(x,d=1)=>Number(x).toLocaleString('tr-TR',{minimumFractionDigits:d,maximumFractionDigits:d});
const trace=steps=>`<details class="trace" open><summary>Çalışan kural ve hesap adımları</summary><ol>${steps.map(x=>`<li>${esc(x)}</li>`).join('')}</ol></details>`;
function shell(input){workspace.innerHTML=`<div class="layout"><aside class="panel input-panel">${input}</aside><div class="panel" id="result" aria-live="polite"></div></div>`;}
function show(tab){
 current=['finance','shop','trial'].includes(tab)?tab:'finance';
 document.documentElement.style.setProperty('--accent',{finance:'#087e71',shop:'#a44913',trial:'#1265a8'}[current]);
 document.documentElement.style.setProperty('--tint',{finance:'#e6f4f1',shop:'#fff0e5',trial:'#eaf3fb'}[current]);
 document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-current',String(b.dataset.tab===current)));
 if(location.hash!=='#'+current)history.replaceState(null,'','#'+current);
 document.querySelectorAll('header a').forEach(a=>a.href='../Sunum/Final_Proje_Tanitim.html#'+({finance:6,shop:7,trial:8}[current]));
 ({finance:financeUI,shop:shopUI,trial:trialUI}[current])();
}
function financeUI(){
 shell(`<h2>FinSight</h2><p>Analist Ece için kaynaklı bir ilk bakış notu hazırlayın.</p><label for="company">Örnek şirket</label><select id="company">${E.companies.map(c=>`<option value="${c.id}">${c.name}</option>`).join('')}</select><label for="fin-task">Araştırma görevi</label><select id="fin-task"><option value="report">Üç yıllık araştırma özeti</option><option value="compare">İki şirketi karşılaştır</option><option value="advice">Bu hisseyi almalı mıyım?</option></select><button class="primary" id="run">Araştırmayı çalıştır</button><div class="callout">Kurgu şirketler ve yıllık kayıtlar. Yatırım tavsiyesi üretilmez.</div><p>Gösterilecek an: Bir sayının yanındaki kayıt kimliğinden veri satırına dönün.</p>`);
 $('#run').onclick=renderFinance;$('#company').onchange=renderFinance;$('#fin-task').onchange=renderFinance;renderFinance();
}
function renderFinance(){
 const task=$('#fin-task').value,r=E.finance($('#company').value),last=r.rows.at(-1);
 if(task==='advice'){$('#result').innerHTML=`<h2>Yatırım kararı kapsam dışında</h2><div class="callout warning">Bu demo al/sat/tut önerisi veya getiri tahmini üretmez. Araştırma özeti ya da şirket karşılaştırması seçebilirsiniz.</div>${trace(['Seçilen görev kapsam kontrolüne girdi.','Tavsiye isteği durduruldu; araştırma seçenekleri sunuldu.'])}`;return;}
 const rows=task==='compare'?E.companies.map(c=>{const f=E.finance(c.id),v=f.rows.at(-1);return `<tr><td>${c.name}</td><td>${num(v.revenue)}</td><td>${num(v.margin)}%</td><td>${num(v.growth)}%</td><td>${c.source} / 2024</td></tr>`;}).join(''):r.rows.map(v=>`<tr><td>${v.year}<small>${v.source}</small></td><td>${num(v.revenue)}</td><td>${num(v.profit)}</td><td>${num(v.margin)}%</td><td>${v.growth==null?'—':num(v.growth)+'%'}</td></tr>`).join('');
 $('#result').innerHTML=`<div class="result-head"><div><h2>${task==='compare'?'Aynı sektör, iki farklı görünüm':r.company.name}</h2><p class="muted">${r.company.sector} · 2022–2024 · milyon USD</p></div><span class="badge">Örnek araştırma taslağı</span></div><div class="metrics"><div class="metric"><span>Son yıl gelir</span><strong>${num(last.revenue,0)}</strong><small>milyon USD</small></div><div class="metric"><span>Net kâr marjı</span><strong>%${num(last.margin)}</strong><small>net kâr / gelir</small></div><div class="metric"><span>2 yıllık gelir CAGR</span><strong>%${num(r.cagr)}</strong><small>(son / ilk)^(1/2) − 1</small></div></div><h3>${task==='compare'?'2024 karşılaştırması':'Finansal kayıtlar'}</h3><div class="table-wrap"><table><thead><tr>${(task==='compare'?['Şirket','Gelir','Net marj','Büyüme','Kayıt']:['Yıl','Gelir','Net kâr','Net marj','Büyüme']).map(s=>`<th>${s}</th>`).join('')}</tr></thead><tbody>${rows}</tbody></table></div><div class="cols"><div><h3>Yönetim notları</h3><ul>${r.company.notes.map(s=>`<li>${s}</li>`).join('')}</ul></div><div><h3>İncelenecek riskler</h3><ul>${r.company.risks.map(s=>`<li>${s}</li>`).join('')}</ul></div></div><div class="callout">Kaynak: <strong>${r.company.source}</strong>. Bu sayılar gerçek bir şirketi temsil etmez. Notlar veri paketindeki metinlerden gelir; model tarafından üretilmez.</div>${trace(r.trace)}<details class="trace"><summary>Kaynak satırlarını göster</summary><pre>${esc(JSON.stringify(r.company.years,null,2))}</pre></details>`;
}
function shopUI(){
 shell(`<h2>ShopOps</h2><p>Ayşe'nin siparişini kontrol edin, iade koşulunu hesaplayın ve talebi onaylayın.</p><label for="order">Örnek sipariş</label><select id="order"><option value="DEMO-1001">1001 · Yeni teslim edilen kulaklık</option><option value="DEMO-1002">1002 · Geç teslim edilen sandalye</option><option value="DEMO-1003">1003 · Yoldaki lamba</option><option value="DEMO-1004">1004 · Tam 14 gün önce teslim</option><option value="DEMO-2001">2001 · Başka müşterinin siparişi</option><option value="MISSING">9999 · Olmayan sipariş</option></select><label for="reason">İade nedeni</label><select id="reason"><option value="changed_mind">Vazgeçtim</option><option value="damaged">Ürün hasarlı</option><option value="wrong_item">Yanlış ürün geldi</option><option value="late">Geç teslim edildi</option></select><button class="primary" id="run">İade koşulunu kontrol et</button><div class="callout">Örnek müşteri oturumu: <strong>Ayşe</strong><br>Simülasyon tarihi: 1 Eylül 2018</div><p>Onay, yalnız bu sekmenin belleğinde örnek talep oluşturur. Ödeme veya gerçek iade yapılmaz.</p>`);
 $('#run').onclick=()=>renderShop();$('#order').onchange=()=>renderShop();$('#reason').onchange=()=>renderShop();renderShop();
}
function renderShop(message='',created=null){
 let r=E.refund($('#order').value,$('#reason').value,requests),o=r.order;if(created)r={...r,code:created.status,label:'Talep oluşturuldu',canRequest:false};
 $('#result').innerHTML=`<div class="result-head"><div><h2>${esc(r.label)}</h2><p class="muted">${o?esc(o.id+' · '+o.item):'Girilen sipariş için erişilebilir kayıt yok.'}</p></div><span class="badge ${r.canRequest?'good':'unknown'}">${r.code}</span></div>${message?`<div class="toast" role="status">${esc(message)}</div>`:''}${o?`<div class="metrics"><div class="metric"><span>Ürün bedeli</span><strong>${num(o.price,2)}</strong><small>BRL</small></div><div class="metric"><span>Kargo</span><strong>${num(o.freight,2)}</strong><small>BRL</small></div><div class="metric"><span>Talep edilebilir tutar</span><strong>${num(r.amount,2)}</strong><small>BRL</small></div></div><div class="table-wrap"><table><tr><th>Teslim</th><th>Tahmini teslim</th><th>Kontrol tarihi</th></tr><tr><td>${o.delivered||'Henüz teslim edilmedi'}</td><td>${o.estimated}</td><td>${E.today}</td></tr></table></div>`:''}${r.canRequest?`<div class="approval"><h3 style="margin-top:0">Talebi oluşturmadan önce</h3><p>${r.freightOnly?'Yalnız kargo bedeli için':'İade için'} ${num(r.amount,2)} BRL tutarında örnek talep açılacak. ${r.review==='PENDING_SENIOR'?'500 BRL üzerindeki tutar kıdemli incelemeye gider.':'Talep destek incelemesine gider.'}</p><label><input type="checkbox" id="consent">Bu sipariş ve tutar için örnek talep oluşturmayı onaylıyorum.</label><button class="primary" id="approve" disabled>Onayla ve örnek talep oluştur</button></div>`:''}${trace(r.trace)}<h3>Bu oturumdaki örnek talepler</h3>${requests.length?requests.map(x=>`<div class="request"><strong>${x.id}</strong> · ${x.orderId} · ${num(x.amount,2)} BRL<br>${x.status==='PENDING_SENIOR'?'Kıdemli inceleme bekliyor':'Destek incelemesi bekliyor'}</div>`).join(''):'<p class="muted">Henüz talep oluşturulmadı.</p>'}`;
 if(r.canRequest){$('#consent').onchange=e=>$('#approve').disabled=!e.target.checked;$('#approve').onclick=()=>{try{const x=E.approve($('#order').value,$('#reason').value,$('#consent').checked,requests);renderShop(x.id+' oluşturuldu. Bu işlem yalnız örnek talep kaydıdır.',x);}catch(e){renderShop(e.message);}};}
}
const options=(items)=>items.map(([v,t])=>`<option value="${v}">${t}</option>`).join('');
function trialUI(){
 shell(`<h2>TrialMatch</h2><p>Sentetik profili örnek protokollerin kriterleriyle karşılaştırın.</p><label for="case">Hazır sentetik vaka</label><select id="case"><option value="full">54 yaş · HER2 pozitif</option><option value="missing">47 yaş · Eksik bilgiler</option><option value="conflict">54 yaş · Beyin metastazı var</option></select><div class="profile-grid"><label for="age">Yaş<input id="age" type="number" min="18" max="100" value="54"></label><label for="her2">HER2<select id="her2">${options([['positive','Pozitif'],['negative','Negatif'],['','Bilinmiyor']])}</select></label><label for="stage">Evre<select id="stage">${options([['III','III'],['II','II'],['IV','IV'],['','Bilinmiyor']])}</select></label><label for="ecog">ECOG<select id="ecog">${options([['','Bilinmiyor'],['0','0'],['1','1'],['2','2']])}</select></label><label for="brain">Beyin metastazı<select id="brain">${options([['no','Yok'],['yes','Var'],['','Bilinmiyor']])}</select></label></div><button class="primary" id="run">Kriterleri karşılaştır</button><div class="callout warning">Tanı, tedavi veya çalışmaya kabul kararı verilmez. Son karar hekim ve çalışma ekibinindir.</div><p>Yalnız sentetik, yapılandırılmış alanlar kullanılır. Gerçek hasta bilgisi girmeyin.</p>`);
 $('#case').onchange=()=>{const mode=$('#case').value;$('#age').value=mode==='missing'?47:54;$('#her2').value=mode==='missing'?'':'positive';$('#stage').value=mode==='missing'?'':'III';$('#ecog').value='';$('#brain').value=mode==='missing'?'':mode==='conflict'?'yes':'no';renderTrial();};
 $('#run').onclick=renderTrial;['age','her2','stage','ecog','brain'].forEach(x=>$('#'+x).onchange=renderTrial);renderTrial();
}
function renderTrial(){
 const age=$('#age').value;if(age!==''&&(!Number.isFinite(Number(age))||Number(age)<18||Number(age)>100)){$('#result').innerHTML='<div class="callout warning">Örnek profil için yaş 18–100 arasında olmalı.</div>';return;}
 const profile={condition:'breast',age:age===''?null:Number(age),her2:$('#her2').value,stage:$('#stage').value,ecog:$('#ecog').value,brain:$('#brain').value},results=E.match(profile);
 const names={age:'Yaş',condition:'Hastalık',her2:'HER2',stage:'Evre',ecog:'ECOG',brain:'Beyin metastazı'},values={breast:'Meme kanseri',positive:'Pozitif',negative:'Negatif',yes:'Var',no:'Yok'};
 const missing=Object.keys(profile).filter(k=>profile[k]===''||profile[k]==null).map(k=>names[k]);
 $('#result').innerHTML=`<div class="result-head"><div><h2>Kriter bazlı ön değerlendirme</h2><p class="muted">3 kurgusal protokol · sentetik meme kanseri profili</p></div><span class="badge">Gerçek çalışma kaydı değil</span></div><div class="callout ${missing.length?'warning':''}"><strong>${missing.length?'Eksik bilgi: '+missing.join(', '):'Örnek profil alanları tamamlandı.'}</strong><br>Bilinmeyen bilgi karşılanmış sayılmaz. Kriterlerin karşılanması, gerçek bir çalışmaya uygunluk veya kabul anlamına gelmez.</div>${results.map(t=>`<article class="trial-card"><div class="heading"><div><h3>${t.name}</h3><p class="muted">${t.id} · Örnek merkez: ${t.city}</p></div><span class="badge ${t.counts.NOT_MET?'bad':t.counts.UNKNOWN?'unknown':'good'}">${t.status}</span></div><details open><summary>${t.counts.MET} karşılandı · ${t.counts.NOT_MET} karşılanmadı · ${t.counts.UNKNOWN} bilinmiyor</summary><div class="table-wrap"><table><thead><tr><th>Örnek kriter</th><th>Profildeki kanıt</th><th>Karar</th></tr></thead><tbody>${t.criteria.map(c=>`<tr><td>${c.label}<small>${t.id}</small></td><td>${c.status==='UNKNOWN'?'Profilde belirtilmedi':esc(names[c.field]+': '+(values[profile[c.field]]||profile[c.field]))}</td><td><span class="badge ${c.status==='MET'?'good':c.status==='UNKNOWN'?'unknown':'bad'}">${c.status}</span></td></tr>`).join('')}</tbody></table></div></details></article>`).join('')}${trace(['Yapılandırılmış sentetik profil okundu.','Yalnız demo veri paketindeki 3 protokol getirildi.','Her kriter ilgili profil alanıyla kod üzerinden karşılaştırıldı.','Boş alanlar UNKNOWN kaldı; uyumsuz kriterler ayrı gösterildi.','Sonuçlar uyumsuz ve eksik kriter sayısına göre sıralandı.'])}`;
}
$('.tabs').addEventListener('click',e=>{const b=e.target.closest('[data-tab]');if(b)show(b.dataset.tab);});
$('#reset').onclick=()=>{requests=[];show(current);};
window.addEventListener('hashchange',()=>show(location.hash.slice(1)));
show(location.hash.slice(1));
