const {test}=require('node:test');const assert=require('node:assert/strict');const E=require('./engine.js');
test('Finans büyüme, marj ve CAGR veriden hesaplanır',()=>{const x=E.finance('atlas');assert.ok(Math.abs(x.rows[2].growth-20)<1e-9);assert.ok(Math.abs(x.rows[2].margin-190/1188*100)<1e-9);assert.ok(Math.abs(x.cagr-((1188/820)**.5-1)*100)<1e-9);});
test('Başka müşteri ve bulunmayan sipariş aynı sonucu verir',()=>{assert.deepEqual(E.refund('DEMO-2001','damaged'),E.refund('MISSING','damaged'));});
test('14 gün sınırı dahil; kargo yalnız gecikme koşuluyla ödenir',()=>{assert.equal(E.refund('DEMO-1004','changed_mind').amount,350);const x=E.refund('DEMO-1002','changed_mind');assert.equal(x.code,'NOT_ELIGIBLE_WINDOW');assert.equal(x.amount,80);assert.equal(x.freightOnly,true);});
test('Hasarlı ürün 30 gün penceresi ve kıdemli eşik',()=>{const x=E.refund('DEMO-1002','damaged');assert.equal(x.amount,700);assert.equal(x.review,'PENDING_SENIOR');});
test('Yoldaki sipariş için talep açılamaz',()=>{assert.equal(E.refund('DEMO-1003','late').canRequest,false);});
test('Açık onay zorunlu, talep sonrası tekrar engellenir',()=>{const r=[];assert.throws(()=>E.approve('DEMO-1001','changed_mind',false,r));assert.equal(r.length,0);E.approve('DEMO-1001','changed_mind',true,r);assert.equal(r.length,1);assert.throws(()=>E.approve('DEMO-1001','changed_mind',true,r));});
test('Eksik klinik veri UNKNOWN; uyumsuz biyobelirteç NOT_MET',()=>{const x=E.match({age:54,condition:'breast',her2:'positive',stage:'III',ecog:'',brain:'no'});const a=x.find(t=>t.id==='DEMO-CT-01');assert.equal(a.criteria.find(c=>c.field==='ecog').status,'UNKNOWN');assert.equal(x.find(t=>t.id==='DEMO-CT-02').criteria.find(c=>c.field==='her2').status,'NOT_MET');});
test('Profil değişimi kriter sonucunu gerçekten değiştirir',()=>{const p={age:54,condition:'breast',her2:'positive',stage:'III',ecog:1,brain:'no'};assert.equal(E.match(p).find(t=>t.id==='DEMO-CT-01').counts.UNKNOWN,0);p.brain='yes';assert.equal(E.match(p).find(t=>t.id==='DEMO-CT-01').counts.NOT_MET,1);});
